sophieliu7/rbnb

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/models/tool.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, db/migrate/20180820122629_create_tools.rb, db/migrate/20180820131307_add_details_to_user.rb, db/schema.rb, test/models/tool_test.rb
@ClaraBsnd @benitoparis hello les guys !!! on a terminé les models avec les validations !! pouvez vous checker notre code ?
=> added User valdiation, added Tool model and validation

app/models/user.rb
@benitoparis @ClaraBsnd @pthimon9 
delete the validation for first name and last name
only 2 lines deleted
=> delete validate first_name and validate last_name in User Model

app/views/tools/index.html.erb
@ClaraBsnd change place for price
=> Front end index tools

Gemfile, Gemfile.lock, db/seeds.rb
@benitoparis @ClaraBsnd @pthimon9 
added seed
=> added seed to run

app/views/tools/edit.html.erb, app/views/tools/index.html.erb, app/views/tools/new.html.erb, db/migrate/20180820165542_add_cat_to_tools.rb
=> added some modification on CSS index + added migration

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb, db/schema.rb
@ClaraBsnd tu valides la navbar? Je ferais une autre MAJ ultérieurement.
=> maj navbar

.gitignore, Gemfile, Gemfile.lock, app/controllers/tools_controller.rb, app/models/tool.rb, app/uploaders/photo_uploader.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, db/migrate/20180821084108_add_photo_to_tools.rb, db/schema.rb
@sophieliu7  @pthimon9  @benitoparis 
J'ai mis les images sur cloudinary, ajouter les gems nécessaires (coudinary et carrierwave) pour uploader les photos, modifié le controller et le model tool (ajout de la colonne photo)
Il faut encore modifié la view (notamment ajout l'option photo dans le form) et les seeds
=> Move image to cloudinary - Uploader photo

app/assets/stylesheets/components/_cards.scss, app/views/tools/index.html.erb, app/views/tools/new.html.erb
@sophieliu7 peux-tu stp valider
=> Frontindextools

.gitignore, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/tools_controller.rb, app/policies/application_policy.rb, app/policies/tool_policy.rb, app/views/tools/edit.html.erb, db/schema.rb, test/policies/tool_policy_test.rb
@benitoparis @ClaraBsnd @sophieliu7 
Guys check the pundit update code please.
=> Adding pundits

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_message.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/reservations_controller.rb, app/models/reservation.rb, app/views/reservations/index.html.erb
@benitoparis @ClaraBsnd @pthimon9
=> worked on reservations view

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_show.scss, app/views/pages/home.html.erb, app/views/shared/_flexboxes.html.erb, app/views/tools/show.html.erb
Modif dela main banner, ajout d'une banner secondaire (lien a faire/à voir), modif marge des cards (width de row)
@sophieliu7 @benitoparis @pthimon9
=> Homepage modif

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/layouts/_body.scss, app/views/layouts/application.html.erb, app/views/shared/_flexboxes.html.erb
Normalement, le footer a fini sa crise d'adolescence et reste là ou il doit être. 
@sophieliu7
=> Tentative de correction du footer

app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
=> changed login design

app/javascript/components/banner.js, app/javascript/packs/application.js, app/views/devise/shared/_links.html.erb, app/views/pages/home.html.erb, package.json, yarn.lock
=> fix bug on login + added JS TYPED

app/views/shared/_navbar.html.erb, db/schema.rb
=> Ajout lien outil

app/assets/stylesheets/pages/_show.scss, app/controllers/application_controller.rb, app/views/tools/show.html.erb
J'ai modifié le controller devise pour avoir le name dans le form de sign up et rajouter nom du proprio sur la page show
=> Name added, controller modif

app/views/devise/registrations/new.html.erb
@pthimon9 ajout champ address sur form user
=> maj formulaire avec address

app/javascript/components/reservation_confirmation.js, app/views/pages/home.html.erb, app/views/tools/index.html.erb
@ClaraBsnd @pthimon9 @benitoparis
=> changed photo

app/assets/stylesheets/pages/_show.scss, app/views/tools/show.html.erb
=> CSS improvement

app/controllers/application_controller.rb, app/javascript/packs/map.js, config/initializers/geocoder.rb
@sophieliu7 j'ai réglé le problème de geoapi google / l'affichage des markers sur la carte
=> maj form new user address

Gemfile, Gemfile.lock, app/controllers/tools_controller.rb, app/models/tool.rb, app/views/tools/index.html.erb, db/seeds.rb
@benitoparis @ClaraBsnd @pthimon9 
Search dispo !!!!
=> added search

app/views/tools/_form.html.erb
=> remove place

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search.scss, app/javascript/components/search.js, app/javascript/packs/application.js, app/views/shared/_navbar.html.erb, app/views/tools/index.html.erb, app/views/tools/show.html.erb
=> Navbar search

app/controllers/reservations_controller.rb
@sophieliu7 
supp res corrigé sans fichiers uploadés
=> supp reservations apres changt branch

app/models/reservation.rb
=> change model resa avec ajout has_one

app/assets/stylesheets/components/_message.scss, app/assets/stylesheets/pages/dashboard.scss, app/views/reservations/index.html.erb, app/views/shared/_my_reservations.html.erb
Tab de la liste des réservations faites par le current user done, images à perfectionner, background color à améliorer
=> Reservations tab

app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_my_tools.scss, app/assets/stylesheets/pages/_user_profile.scss, app/javascript/components/tab.js, app/models/tool.rb, app/views/pages/dashboard.html.erb, app/views/shared/_my_reservations.html.erb, app/views/shared/_my_tools.html.erb, app/views/tools/index.html.erb, db/schema.rb
@sophieliu7 
creation d'un dependent destroy reservation/tool
view des tools du current user
=> My tool view

app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
@ClaraBsnd @sophieliu7 
modif link to categories on homepage --> search
modif dropdown on navbar
modif link to categories on navbar  --> search
plse review
=> change dropdow on navbar & category links on home page & navebar

app/models/tool.rb, db/schema.rb
@sophieliu7 @ClaraBsnd 
category in search
=> Category search

app/views/shared/_modal_tools_resa.html.erb, app/views/shared/_my_tools.html.erb
Creattion de la modal pour voir les reservations sur mes propres tools. 
Select à travailler
@pthimon9 
@sophieliu7 
@benitoparis
=> Creation modal des tools

app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_my_tools.scss, app/assets/stylesheets/pages/_user_profile.scss, app/controllers/pages_controller.rb, app/models/tool.rb, app/views/shared/_modal_tools_resa.html.erb, app/views/shared/_my_profil.html.erb, app/views/shared/_my_tools.html.erb, db/schema.rb
Modal donee
changement de couleur des liens
=> Migration column on user

app/views/shared/_navbar.html.erb
Ajout lien vers dashboard dans la navbar
=> ajout du lien vers dashboard

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_footer.scss, app/views/tools/index.html.erb, db/schema.rb
=> Front index

app/views/tools/index.html.erb, app/views/tools/show.html.erb
=> tool.user.address

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb
@ClaraBsnd @sophieliu7 @benitoparis 
photo user uploading
& photo on navbar
=> uploading user photo & display on navbar

app/views/shared/_my_profil.html.erb, app/views/tools/show.html.erb
=> photo done

app/views/tools/show.html.erb
=> description

app/views/shared/_my_reservations.html.erb
=> add link on my resa
